<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => 'b9b5274af85faea57344dda197ef0be6',
  'DATABASE_URL' => 'postgresql://app:!ChangeMe!@127.0.0.1:5432/app?serverVersion=15&charset=utf8',
  'ASSETS_VERSION' => '1.0.3',
  'GLOBAL_URL' => 'http://dev.luvmystory.com',
  'WKHTMLTOPDF_PATH' => '/usr/local/bin/wkhtmltopdf',
  'WKHTMLTOIMAGE_PATH' => '/usr/local/bin/wkhtmltoimage',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
);
