<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => 'b9b5274af85faea57344dda197ef0be6',
  'DATABASE_URL' => 'mysql://root:@127.0.0.1:3306/luvmystory?serverVersion=8&charset=utf8mb4',
  'ASSETS_VERSION' => '1.0.3',
  'GLOBAL_URL' => 'http://dev.luvmystory.com',
);
