<?php

namespace App\Repository;

use App\Entity\SchduleEntity;

/**
 * SchdeulePaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchedulePaymentRepository extends \Doctrine\ORM\EntityRepository
{

    public function ajax_list(array $get, $userData){

        $columns = array(
            array('sp.`payment_date`', "sp.`payment_date`", "paymentDate"),
            array('sp.`payment_gateway`', 'sp.`payment_gateway`', 'geteway'),
            array('s.`schedule_type`', 's.`schedule_type`', 'schedule'),
            array('sp.`amount`', "sp.`amount`", 'price'),
            array('sp.`note`', "sp.`notes`", 'notes'),
            array('sp.`id`', "sp.`id`"),

        );
        $asColumns = array();

        $select = "SELECT";
        $from = "FROM `schedule_payment` sp";
        $sqlWhere = " WHERE sp.`is_deleted` = 0";
        $joins = " LEFT JOIN `schedule` s ON s.`id` = sp.`schedule_id`";
        $groupBy = "";
        $orderBy = " ORDER BY sp.`id` DESC";
        $limit = "";
        $stmtParams = array();

        foreach($columns as $key => $column) {
            $select .= ($key > 0 ? ', ' : ' ') . $column[1] . (isset($column[2]) ? ' AS ' . $column[2] : '');
        }

        if(isset($userData['type']) && $userData['type'] == 'Client'){
            $stmtParams['clientId'] = $userData['id'];
            $sqlWhere.= ' AND s.`user_id` = :clientId';
        }


        // /*
        //  * Ordering
        //  */
        // foreach($get['columns'] as $key => $column) {
        //     if($column['orderable']=='true') {
        //         if(isSet($get['order'])) {
        //             foreach($get['order'] as $order) {
        //                 if($order['column']==$key) {
        //                     $orderBy .= (!empty($orderBy) ? ', ' : 'ORDER BY ') . $columns[$key][0] . (!empty($order['dir']) ? ' ' . $order['dir'] : '');
        //                 }
        //             }
        //         }
        //     }
        // }

        /*
         * Filtering
         */
        if(isset($get['search']) && $get['search']['value'] != ''){
            $aLikes = array();
            foreach($get['columns'] as $key => $column) {
                if($column['searchable']=='true') {
                    $aLikes[] = $columns[$key][0] . ' LIKE :searchValue';
                }
            }
            foreach($asColumns as $asColumn) {
                $aLikes[] = $asColumn . ' LIKE :searchValue';
            }
            if(count($aLikes)) {
                $sqlWhere .= (!empty($sqlWhere) ? ' AND ' : 'WHERE ') . '(' . implode(' OR ', $aLikes) . ')';
                $stmtParams['searchValue'] = "%" . $get['search']['value'] . "%";
            }
        }

        /* Set Limit and Length */
        if(isset( $get['start'] ) && $get['length'] != '-1'){
            $limit = 'LIMIT ' . (int)$get['start'] . ',' . (int)$get['length'];
        }

        $sql = "$select $from $joins $sqlWhere $groupBy $orderBy";
        $query = $this->getEntityManager()->getConnection()->prepare($sql);
     

        foreach($stmtParams as $k => $v){
            $query->bindValue($k, $v);

        }
        $res = $query->executeQuery();
        $result_count = $res->fetchAllAssociative();
        $sql = "$select $from $joins $sqlWhere $groupBy $orderBy $limit";
        $query = $this->getEntityManager()->getConnection()->prepare($sql);
        foreach($stmtParams as $k => $v){
            $query->bindValue($k, $v);

        }
        $res = $query->executeQuery();
        $result = $res->fetchAllAssociative();

        /* Data Count */
        $recordsTotal = count($result_count);

        /*
         * Output
         */
        $output = array(
            "draw" => intval($get['draw']),
            "recordsTotal" => $recordsTotal,
            "recordsFiltered" => $recordsTotal,
            "data" => array()
        );

        $url = $get['url'];
        $formUrl = '';
        foreach($result as $row) {

            $id = base64_encode($row['id']);


            $values = array(
                $row['paymentDate'],
                $row['gateway'],
                $row['schedule'],
                $row['price'],
                $row['notes']
            );

            $output['data'][] = $values;
        }

        unset($result);

        return $output;
    }

   
   
}
